# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-25 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='bios',
        ),
    ]
